# Generated by Django 5.2.3 on 2025-06-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("charge", "Charge"), ("payment", "Payment")],
                max_length=7,
                null=True,
            ),
        ),
    ]
